version: '3.9'

services:

  db:
    build:
      dockerfile: ./Dockerfile 
    container_name: redshift-instance 
    restart: always
    environment:
      POSTGRES_PASSWORD: ander123
    ports:
     - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./sql_nivelacion:/sql_nivelacion
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080