version: '3.9'

services:

  db:
    image: postgres
    container_name: redshift-instance 
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ander123
    ports:
     - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - ./clase:/clase
      - ./sql-etl-process:/sql-etl-process